spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/elearning_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:QmFzZTY0RW5jb2RlZFNlY3JldEtleUZvckRldk9ubHlKb25nRW5vdWdoIQ==}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
